### ISSUE TITLE
Support for 10x10x10, 11x11x11, etc

### ISSUE THREAD

**Issue by dwalton76** [cubing/alg.cubing.net#139]
I've written an [NxNxN solver](https://github.com/dwalton76/rubiks-cube-NxNxN-solver), part of the solution is a link to alg.cubing.net so you can see exactly how the cube is solved.  al.cubing.net support for cubes larger than 9x9x9 would be cool.

**Comment by lgarron** [comment]
Implemented, thanks to @supersammy7000!
