### ISSUE TITLE
[enhancement] og:image being intial state when "alg" is in the url, and other og: properties

### ISSUE THREAD

**Issue by robertvandeneynde** [cubing/alg.cubing.net#145]
When sharing a link on facebook or Whatsapp, the image is not very useful, we see a solved cube, that's probably not what we want. I suggest when the url has the query parameter "type=alg", the image should be the intial state of the cube (ie. what it solves).

For example I share this nice OLL : https://alg.cubing.net/?title=Untying%20(OLL)&stage=PLL&type=alg&alg=F_R_U-_R-_U-_R_U_R-_F-

The preview would be with the title "Untying (OLL)" with this image : 

![screenshot_2018-06-17_22 11_58](https://user-images.githubusercontent.com/7661856/41511659-a9ff0af6-727b-11e8-8c45-8152e119b84e.png)

This has to be server side unfortunately but i suggest that the server would write this <meta> properties : 

```html
    <meta property="og:image" content="https://alg.cubing.net/initial-state?title=Untying%20(OLL)&stage=PLL&type=alg&alg=F_R_U-_R-_U-_R_U_R-_F-" />
    <meta property="og:title" content="Untying (OLL)"/>
    <meta property="og:description" content="F R U' R' U' R U R' F'"/>
```

For the image, a separate url "initial-state" would be coded on the server to generate the image, the browser would cache it, but if performance is concerned, the image can be cached on the server. The image size can be quite small, well, being a cube. But one could look at Facebook/Reddit recommendation [here](https://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit) or [here](https://developers.facebook.com/docs/sharing/best-practices).

**Comment by lgarron** [comment]
Yeah, this is issue #54. I'll think about this after the ongoing `v2` rewrite, but for now I can't dedicate time to it. :-(

(If you have more thoughts, feel free to continue at #54.)

**Comment by robertvandeneynde** [comment]
I think I will first code a url on my server and redirect it to alg.cubing.net, then maybe it will be easier to merge it later.

**Comment by lgarron** [comment]
> I think I will first code a url on my server and redirect it to alg.cubing.net, then maybe it will be easier to merge it later !

Will be glad to see what you come up with!

I will probably be very picky about shipping anything to production if the images don't look exactly like they do on the website, but it would certainly be nice to have somewhere to start from.
