### ISSUE TITLE
Automatically download image after pasting the alg

### ISSUE THREAD

**Issue by abunickabhi** [cubing/alg.cubing.net#162]
Till now, if I had to download an image from alg.cubing, I have to do right link, save image as..., and the the file name and local folder where it has to be kept in.

Since I need to do this process for thousands of images, it takes a lot of time. 

Is there a way, the image gets downloaded as soon as I paste the algorithm on alg.cubing?

**Comment by lgarron** [comment]
I can write you a custom tool until alg.cubing.net has moved to Twizzle.

Do you need any particular features? Do you need to be able to specify the file names? Do you need to include any display options?

**Comment by abunickabhi** [comment]
I do not need any particular feature, the file naming can go like how it is named in batches, a0001, a0002 ,...
The display option should be the cube image itself, with projection video, and only the DB, DL and BD sticker hidden, in the opaque video.

I will be making the introduction video for your series on twizzle YT explanation soon.

**Comment by lgarron** [comment]
For the record, I've written this for now:

https://experiments.cubing.net/cubing.js/multi-alg/index.html

**Comment by abunickabhi** [comment]
Thanks I have checked it along with the video, with code explanation that you made. It has helped me a lot in my saving time while getting images for algorithms. 

Thanks Lucas!
