### ISSUE TITLE
Features: Cube Record

### ISSUE THREAD

**Issue by zqktlwi4fecvo6ri** [cubing/alg.cubing.net#165]
Idk about the difficulties, but can I suggest a feature for recording the Cube Alg Rotations?

**Comment by lgarron** [comment]
Could you specify more that is being recorded? Do you want to record move input, record an animation, or something else?

**Comment by zqktlwi4fecvo6ri** [comment]
> Could you specify more that is being recorded? Do you want to record move input, record an animation, or something else?

record the animation of the cube, sorry for the ambiguous

**Comment by lgarron** [comment]
I see. In that case, I would recommend using https://chrome.google.com/webstore/detail/canvas-capture/pnhaaddlgbpchligciolcdjgndcpelee?hl=en-US on alg.cubing.net

twizzle.net will support animations in the future, but the feature is not ready yet.

**Comment by zqktlwi4fecvo6ri** [comment]
thanks!
